# You can configure every mob name (without spaces) or a default!
chargeSameMob: false
chargeXP: false
chargeBoth: false
chargeMultipleAmounts: false
confirmation:
  enabled: false
  delay: 30
default:
  break:
    money: 10.5
    xp: 100
  change:
    money: 10.5
    xp: 100
  place:
    money: 10.5
    xp: 100
pig:
  break:
    money: 7.25
    xp: 200
  change:
    money: 7.25
    xp: 200
  place:
    money: 7.25
    xp: 200
cow:
  break:
    money: 0.0
    xp: 20
  change:
    money: 0.0
    xp: 20
  place:
    money: 0.0
    xp: 20
